Use latest as default instead of individual numbers for apiVersion
RoadieHQ/backstage-plugin-jira pull request #19
Opened 2020-12-07 10:44 UTC by O5ten

Instead of using a hard-number for the JIRA API version you should use the /latest/ resource parameter which will use the latest one present in the target JIRA.

2020-12-09 14:49 UTC, adamdmharvey commented
Great idea!

2020-12-09 19:36 UTC, mcalus3 approved these changes

2020-12-09 19:39 UTC, mcalus3 commented
It needs to be rebased before merge, so I'll also add a request to remove the schema from `package.json` file as it is no more needed.

2020-12-09 19:43 UTC, mcalus3 requested changes
I see that I can't highlight the `package.json` code in github review, so will show it in a screenshot:

![image](https://user-images.githubusercontent.com/24685983/101679082-227f3c00-3a5f-11eb-8a99-1b7b3a217818.png)

2020-12-09 20:34 UTC, O5ten commented
It's probably a good idea for someone using a cloud jira (and thereby actually using v3) that nothing breaks with this as i haven't had the possibility to test this properly myself.

2020-12-09 21:58 UTC, mcalus3 commented
@lewtakm tested it with cloud jira :)

2020-12-10 12:32 UTC, mcalus3 approved these changes

2020-12-10 12:32 UTC, merged